const $=id=>document.getElementById(id);let mode='demo',paused=false,history=[],port=null,reader=null,lastTime=0,prevTemp=null,filteredRate=0,lastArrival=0,stale=false,simValue=32,session=0;const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function log(t){const e=document.createElement('div');e.textContent=new Date().toLocaleTimeString()+'  '+t;$('log').prepend(e);while($('log').children.length>12)$('log').lastChild.remove()}
function weights(x,scale){return [clamp(-x/scale,0,1),Math.max(0,1-Math.abs(x)/scale),clamp(x/scale,0,1)]}
function fuzzy(e,r){const a=weights(e,5),b=weights(r,2),rules=[[10,15,40],[20,35,65],[60,80,100]];let sum=0,total=0;for(let i=0;i<3;i++)for(let j=0;j<3;j++){let w=a[i]*b[j];sum+=w*rules[i][j];total+=w}return sum/total}
function settings(){let target=Number($('target').value),alert=Number($('alert').value);if(!Number.isFinite(target)||target<10||target>50||!Number.isFinite(alert)||alert<15||alert>70||alert<=target)return null;return {target,alert}}
function ingest(t,c){if(!Number.isFinite(t)||!Number.isFinite(c)||t< -40||t>125||Math.abs(c)>1000){log('Invalid telemetry rejected');return}let set=settings();if(!set){unavailable('Set valid target and a higher warning threshold.');return}let now=Date.now();if(prevTemp!==null&&lastTime&&now-lastTime>100&&now-lastTime<5000){let dt=(now-lastTime)/60000,raw=(t-prevTemp)/dt,alpha=1-Math.exp(-(now-lastTime)/5000);filteredRate+=alpha*(raw-filteredRate)}else filteredRate=0;prevTemp=t;lastTime=now;lastArrival=now;stale=false;let e=t-set.target,d=fuzzy(e,filteredRate);history.push({time:new Date(now).toISOString(),mode,temperature:t,current:c,error:e,rate:filteredRate,demand:d,target:set.target,warning:set.alert});if(history.length>10000)history.shift();$('temp').innerHTML=t.toFixed(1)+' <span>°C</span>';$('current').innerHTML=c.toFixed(2)+' <span>A</span>';$('demand').innerHTML=d.toFixed(0)+' <span>%</span>';$('bar').style.width=d+'%';$('demandLabel').textContent=(d<30?'LOW':d<65?'MEDIUM':'HIGH')+' calculated demand • display only';$('error').textContent=(e>=0?'+':'')+e.toFixed(1)+' °C';$('rate').textContent=(filteredRate>=0?'+':'')+filteredRate.toFixed(2)+' °C/min';$('decision').textContent=t>=set.alert?'⚠ Above demo warning threshold — no cutoff connected.':e>0?'Above target: cooling demand increased.':'Below / near target: demand follows temperature trend.';$('decision').style.color=t>=set.alert?'#ff8a8a':'#ffbd69';$('last').textContent='Updated '+new Date(now).toLocaleTimeString();draw()}
function unavailable(reason){$('temp').innerHTML='-- <span>°C</span>';$('current').innerHTML='-- <span>A</span>';$('demand').innerHTML='-- <span>%</span>';$('bar').style.width='0%';$('demandLabel').textContent=reason;$('error').textContent='-- °C';$('rate').textContent='-- °C/min';$('decision').textContent=reason}
function draw(){let cv=$('chart'),r=cv.getBoundingClientRect(),dpi=devicePixelRatio||1;cv.width=r.width*dpi;cv.height=r.height*dpi;let ctx=cv.getContext('2d');ctx.scale(dpi,dpi);let w=r.width,h=r.height,L=36,R=36,T=23,B=28;ctx.font='10px system-ui';for(let i=0;i<=4;i++){let y=T+(h-T-B)*i/4;ctx.strokeStyle='#26354a';ctx.beginPath();ctx.moveTo(L,y);ctx.lineTo(w-R,y);ctx.stroke();ctx.fillStyle='#91a3bb';ctx.fillText(String(60-i*15),4,y+3);ctx.fillText(String(100-i*25),w-R+8,y+3)}ctx.fillStyle='#4be0bd';ctx.fillText('°C',5,10);ctx.fillStyle='#67a8ff';ctx.fillText('%',w-25,10);let data=history.slice(-120);[['temperature',60,'#4be0bd'],['demand',100,'#67a8ff']].forEach(([key,max,col])=>{ctx.strokeStyle=col;ctx.lineWidth=2;ctx.beginPath();data.forEach((v,i)=>{let x=L+(w-L-R)*i/119,y=T+(h-T-B)*(1-clamp(v[key]/max,0,1));i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()});ctx.fillStyle='#91a3bb';ctx.fillText('Older',L,h-6);ctx.fillText('Newest →',w-98,h-6)}
function clearData(){history=[];prevTemp=null;filteredRate=0;lastTime=0;lastArrival=0;stale=false;draw()}
function setMode(m){mode=m;$('modeBadge').textContent=m==='demo'?'● SIMULATION MODE':'● USB SERIAL MODE';$('notice').textContent=m==='demo'?'DEMO DATA — simulated readings, not connected to a battery. Pump automation is not connected. Cooling demand ≠ actual pump speed.':'USB SERIAL — incoming sensor data. Demand is calculated in this browser; no commands are sent to ESP32. Actual pump operation is not verified.';['simTemp','simCurrent','pause'].forEach(id=>$(id).disabled=m!=='demo')}
async function disconnect(){session++;if(reader){try{await reader.cancel()}catch(e){}}if(port){try{await port.close()}catch(e){}}port=null;reader=null;$('connect').textContent='Connect ESP32'}
$('connect').onclick=async()=>{if(port){await disconnect();unavailable('Disconnected. Choose Reset demo or reconnect.');log('USB disconnected');return}if(!navigator.serial){log('Web Serial unavailable: use desktop Chrome / Edge on localhost or open the HTML directly.');alert('USB Serial needs desktop Chrome / Edge. Download this HTML and open it locally, or use localhost. Demo mode still works here.');return}try{let p=await navigator.serial.requestPort();await p.open({baudRate:Number($('baud').value)});port=p;let mySession=++session;clearData();setMode('serial');lastArrival=Date.now();unavailable('Waiting for valid ESP32 JSON…');$('connect').textContent='Disconnect';log('USB connected. Waiting for newline-delimited JSON.');reader=p.readable.getReader();let localReader=reader,decoder=new TextDecoder(),buffer='';try{while(mySession===session){let {value,done}=await localReader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});let parts=buffer.split('\n');buffer=parts.pop();if(buffer.length>4096){buffer='';log('Oversized serial line discarded')}for(let l of parts){if(!l.trim())continue;try{let v=JSON.parse(l);if(typeof v.temperature!=='number'||typeof v.current!=='number')throw Error();ingest(v.temperature,v.current)}catch(e){log('Skipped line: expected numeric temperature and current JSON fields')}}}}finally{localReader.releaseLock();if(mySession===session){reader=null;try{await p.close()}catch(e){}port=null;$('connect').textContent='Connect ESP32';unavailable('Serial stream ended — readings unavailable.');log('Serial stream ended')}}}catch(e){log('Connection unavailable: '+e.message)}};
$('demo').onclick=async()=>{await disconnect();clearData();setMode('demo');paused=false;$('pause').textContent='Pause demo';simValue=Number($('simTemp').value);ingest(simValue,Number($('simCurrent').value));log('Simulation restarted — not hardware data')};$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'Resume demo':'Pause demo';if(paused){unavailable('Demo paused — historical chart retained');log('Simulation paused')}else{prevTemp=null;log('Simulation resumed')}};
['simTemp','simCurrent'].forEach(id=>$(id).oninput=()=>$(id+'Label').textContent=$(id).value+(id==='simTemp'?' °C':' A'));
['target','alert'].forEach(id=>$(id).onchange=()=>{if(!settings()){log('Invalid settings: warning must exceed target; check allowed ranges.');unavailable('Invalid demonstration settings')}else log('Demo settings updated; not validated safety limits')});
$('export').onclick=()=>{if(!history.length){log('No data to export');return}let keys=['time','mode','temperature','current','error','rate','demand','target','warning'];let csv=keys.join(',')+'\n'+history.map(v=>keys.map(k=>v[k]).join(',')).join('\n');let u=URL.createObjectURL(new Blob([csv],{type:'text/csv'})),a=document.createElement('a');a.href=u;a.download='NexGenEV_'+mode+'_telemetry.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);log('CSV exported: '+history.length+' samples (includes data-source mode)')};
setInterval(()=>{if(mode==='demo'&&!paused){simValue+=(Number($('simTemp').value)-simValue)*.08;ingest(simValue,Number($('simCurrent').value))}else if(mode==='serial'&&lastArrival&&Date.now()-lastArrival>5000&&!stale){stale=true;unavailable('STALE DATA — no valid reading for 5 seconds');log('Telemetry stale: demand hidden until fresh readings arrive')}},1000);window.addEventListener('resize',draw);ingest(32,3);log('Demo initialized. Fuzzy inference runs locally in the browser.');
